package servicesconstant

type ErrorMessage string

const (
	ErrorMessage_RefreshTokenNotFound       ErrorMessage = "empty refresh token"
	ErrorMessage_NoContent                  ErrorMessage = "No Content"
	ErrorMessage_BuildLogoutRequest         ErrorMessage = "error building logout request"
	ErrorMessage_ConnectionIDP              ErrorMessage = "cannot logout from IDP"
	ErrorMessage_ReturnFromIDP              ErrorMessage = "IDP Return"
	ErrorMessage_BuildRefreshRequest        ErrorMessage = "error building refresh request"
	ErrorMessage_RefreshTokenFailed         ErrorMessage = "Unable to refresh session. The refresh token is expired or invalid."
	ErrorMessage_RefreshDecodeFailed        ErrorMessage = "Unable to process refresh response. The response format is invalid or unreadable."
	ErrorMessage_EmptyIDPUrl                ErrorMessage = "Empty IDP Url"
	ErrorMessage_OTPExpired                 ErrorMessage = "OTP has expired"
	ErrorMessage_OTPInvalid                 ErrorMessage = "OTP is invalid"
	ErrorMessage_RegistrationNotFound       ErrorMessage = "Registration not found"
	ErrorMessage_RateLimited                ErrorMessage = "Too many requests. Please try again later."
	ErrorMessage_RegistrationStateMismatch  ErrorMessage = "Registration State Mismatch"
	ErrorMessage_MissingRegID               ErrorMessage = "Missing regId"
	ErrorMessage_AccessTokenNotFound        ErrorMessage = "empty access token"
	ErrorMessage_ForbiddenState             ErrorMessage = "Forbidden State"
	ErrorMessage_ProjectNotFound            ErrorMessage = "Project not found"
	ErrorMessage_UserNotFound               ErrorMessage = "User not found"
	ErrorMessge_PersistAuthStateFailed      ErrorMessage = "Persist auth state failed"
	ErrorMessage_DuplicateEducationRecord   ErrorMessage = "Duplicate education record"
	ErrorMessage_EducationNotFound          ErrorMessage = "Education record not found"
	ErrorMessage_UserNotFoundEducation      ErrorMessage = "User has no education records"
	ErrorMessage_DuplicateEducationOnUpdate ErrorMessage = "Updating this education would duplicate an existing record"
	ErrorMessage_PermissionDenied           ErrorMessage = "Permission Denied"
	ErrorMessage_CourseBookmarkNotFound     ErrorMessage = "Course bookmark not found"
	ErrorMessage_CourseNotFound             ErrorMessage = "Course not found"
	ErrorMessage_CourseCertificateNotFound  ErrorMessage = "Course certificate not found"
	ErrorMessage_CourseEnrollmentNotFound   ErrorMessage = "Course enrollment not found"
	ErrorMessage_CourseReviewNotFound       ErrorMessage = "Course Review not found"

	ErrorCode                           = "9999"
	ErrorCodeRefreshTokenNotFound       = "9998"
	ErrorCodeNoContent                  = "9997"
	ErrorCodeBuildLogoutRequest         = "9996"
	ErrorCodeConnectionIDP              = "9995"
	ErrorCodeReturnFromIDP              = "9994"
	ErrorCodeBuildRefreshRequest        = "9993"
	ErrorCodeRefreshTokenFailed         = "9992"
	ErrorCodeRefreshDecodeFailed        = "9991"
	ErrorCodeEmptyIDPUrl                = "9990"
	ErrorCodeRegistrationNotFound       = "9989"
	ErrorCodeBadRequest                 = "9988"
	ErrorCodeAccessTokenNotFound        = "9987"
	ErrorCodeForbiddenState             = "9986"
	ErrorCodeProjectNotFound            = "9985"
	ErrorCodeUserNotFound               = "9984"
	ErrorCodeDuplicateEducationRecord   = "9983"
	ErrorCodeEducationNotFound          = "9982"
	ErrorCodeUserNotFoundEducation      = "9981"
	ErrorCodeDuplicateEducationOnUpdate = "9980"
	ErrorCodePermissionDenied           = "9979"
	ErrorCodeInternalServerError        = "5000"
	ErrorCodeCourseBookmarkNotFound     = "9978"
	ErrorCodeCourseNotFound             = "9977"
	ErrorCodeCourseCertificateNotFound  = "9979"
	ErrorCodeCourseEnrollmentNotFound   = "9980"
	ErrorCodeCourseReviewNotFound       = "9976"
	ErrorCodeDataNotFound               = "9975"
	ErrorCodeUnauthorized               = "4010"
)
